### ISSUE TITLE
in export keystore, crash when type in wrong password

### ISSUE THREAD

**Issue by yimenglovesai** [Loopring/loopr-ios#71] opened 2018-04-22 06:29 UTC
<img width="1028" alt="screen shot 2018-04-21 at 11 28 24 pm" src="https://user-images.githubusercontent.com/38386601/39092162-cc3b4da6-45bb-11e8-848a-1735e549523d.png">

**Comment by yimenglovesai** [comment] 2018-04-22 06:29
<img width="510" alt="screen shot 2018-04-21 at 11 28 34 pm" src="https://user-images.githubusercontent.com/38386601/39092164-d2f04f8e-45bb-11e8-8994-71a6f8533442.png">
crash place

**Comment by xiaowheat** [comment] 2018-04-22 07:26
@yimenglovesai If you type the correct password, does it crash?

**Comment by yimenglovesai** [comment] 2018-04-23 01:04
yes, i tried. i setup a break point in wallet, seems the password is "", which is wrong.

**Comment by xiaowheat** [comment] 2018-04-23 05:28
This one should be fixed in dce3cc2ef059a83d770e4c317f0e7cdc96b0ce2f You need to delete the app and reinstall it.

**Comment by xiaowheat** [comment] 2018-04-30 20:05
The root cause is importing a wallet using a private key doesn't need a password. However, exporting a keystone requires a password. The workflow should be asking users to input a password before generating a keystone if the wallet is imported using a private key.

**Comment by xiaowheat** [comment] 2018-08-12 07:31
已修复

**Closed by xiaowheat** 2018-08-12 07:31 UTC
